; working on getting yakker command-line arguments parsed.
; remaining issues:
; (1) what to do about errors, e.g., misspelled option
; (2) how to handle arguments that start with '-' but are not options
; (3) how to report the error to the user
; (4) what about args containing NULs
;
@begin {
(*******************************************************************************
 * Copyright (c) 2010 AT&T.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Trevor Jim and Yitzhak Mandelbaum
 *******************************************************************************)

open Yak
type plugin =
  | Dypgen_PI of bool (** flag indicating whether the generated grammar should be faux-scannerless. *)

type transformation = Add_LR1_lookahead_Tx

type command =
| Attributes_cmd
| Close_under_core_cmd
| Compile_cmd
| Copyrule_cmd
| Desugar_cmd
| Dispatch_cmd
| Dot_cmd
| Exec_cmd
| Extract_cmd
| Fuse_cmd
| Hash_cmd
| Info_cmd
| Inline_regular_cmd
| Lexer_cmd
| Lift_cmd
| Lookahead_analysis_cmd
| Minus_cmd
| Precedence_analysis_cmd
| Print_gil_cmd
| Print_gul_cmd
| Print_npreds_cmd
| Print_relevance_cmd
| Rfc_cmd
| Strip_late_actions_cmd
| Subset_cmd
| Transform_cmd
| Translate_cmd
| Tx_prec_cmd
| Unroll_star_cmd
| Wrap_cmd

let cmd = ref Print_gul_cmd
let files = ref []
let roots = ref []
let exec_l = ref []
let rfc_num = ref 0
let translate_plugin = ref (Dypgen_PI false)
let transforms = ref []
let only = ref false

type backend =
  | Fun_BE   (** Functional backend (parser combinators).*)
  | Peg_BE of bool (** PEG backend. argument indicates whether
                       to use more liberal (PADS-style) star. *)
  | Trans_BE (** Transducer backend. *)

let backend = ref Trans_BE
}
cmd-line-args = command$c *args eof { cmd := c }.
o = %d0 .
arg = 1*CHAR !CHAR .
file = (CHAR - "-") *CHAR !CHAR .
transformation =
      "add-lr1-lookahead" { Add_LR1_lookahead_Tx }
          .
command =
        "attributes" o                    { Attributes_cmd }
      | "close-under-core" o              { Close_under_core_cmd }
      | "compile" o                       { Compile_cmd }
      | "desugar" o                       { Desugar_cmd }
      | "dispatch" o                      { Dispatch_cmd }
      | "dot" o                           { Dot_cmd }
      | "exec" o arg$f *(o arg$x {x})$l o { files := f::!files; exec_l := l; Exec_cmd }
      | "extract" o                       { Extract_cmd }
      | "fuse" o                          { Compileopt.coalesce := true; Fuse_cmd }
      | "hash" o                          { Hash_cmd }
      | "info" o                          { Info_cmd }
      | "inline-regular" o                { Compileopt.inline_regular := true; Inline_regular_cmd }
      | "lexer" o                         { Lexer_cmd }
      | "lift" o                          { Lift_cmd }
      | "lookahead-analysis" o            { Lookahead_analysis_cmd }
      | "minus" o                         { Minus_cmd }
      | "precedence" o                    { Tx_prec_cmd }
      | "precedence-analysis" o           { Precedence_analysis_cmd }
      | "print" o                         { Print_gul_cmd }
      | "print-gil" o                     { Print_gil_cmd }
      | "print-npreds" o                  { Print_npreds_cmd }
      | "print-nullable-predicates" o     { Print_npreds_cmd }
      | "print-relevance" o               { Print_relevance_cmd }
      | "rfc" (1*DIGIT)$n o               { try rfc_num := int_of_string n; Rfc_cmd with _ -> failwith "Invalid RFC number" }
      | "strip-late-actions" o            { Strip_late_actions_cmd }
      | "subset" o                        { Subset_cmd }
      | "transform" o transformation$tx *("," transformation$x {x})$txs o { transforms := (tx::txs); Transform_cmd }
      | "translate" o
           ("dypgen" {Dypgen_PI false}
           |"dypgen-scannerless"
                    {Dypgen_PI true})$t o { translate_plugin := t; Translate_cmd }
      | "unroll-star" o                   { if !Compileopt.unroll_star_n<1 then Compileopt.unroll_star_n := 1; Unroll_star_cmd }
      | "wrap" o                          { Wrap_cmd }

args =
        "-backend" o
          ( "fun" {Fun_BE}
          | "tx"  {Trans_BE}
          | "peg-strict" {Peg_BE false}
          | "peg" {Peg_BE true} )$b o     { backend := b }
      | "-case-insensitive" o             { Compileopt.case_sensitive := false }
      | "-check-labels" o                 { Compileopt.check_labels := true }
      | "-counter" o (1*DIGIT)$n o        { Variables.counter := (int_of_string n) }
      | "-inline-cs" o                    { Compileopt.inline_cs := true }
      | "-inline-regular" o               { Compileopt.inline_regular := true }
      | "-lookahead" o                    { Compileopt.lookahead := true }
      | "-new-engine" o                   { Yak.Pami.new_engine_flag := true }
      | "-no-coalesce" o                  { Compileopt.coalesce := false }
      | "-only" o                         { only := true }
      | "-root" o arg$x o                 { roots := x::!roots }
      | "-unroll-star" o (1*DIGIT)$n o    { Compileopt.unroll_star_n := (int_of_string n) }
      | "-v" o                            { Yak.Logging.add_features Yak.Logging.Features.verbose }
      | file$f o                          { files := f::!files }
.
eof = "" !OCTET .
@end {

let args_ykbuf = Yak.YkBuf.strings2buf Sys.argv 1
let what_arg = Yak.YkBuf.stringsposn2string Sys.argv 1
let process() =
    (try
      ignore(parse args_ykbuf); (!cmd, List.rev !files, List.rev !roots, !backend)
    with
      Yak.Pami.Parse_error("Error at byte.", i, _, _) ->
        let bad_arg = what_arg i in
        let bad = Sys.argv.(bad_arg) in
        if bad_arg = 1 then
          raise(Failure(Printf.sprintf "Unrecognized command '%s'" bad))
        else if String.length bad > 0 && String.get bad 0 = '-' then
          raise(Failure(Printf.sprintf "Unrecognized option '%s'" bad))
        else
          raise(Failure(Printf.sprintf "Bad argument '%s'" bad)))
}
